const Project = require("./classes/Project/Project");

const keypress = async () => {
  process.stdin.setRawMode(true);
  return new Promise((resolve) =>
    process.stdin.once("data", (data) => {
      const byteArray = [...data];
      if (byteArray.length > 0 && byteArray[0] === 3) {
        console.log("^C");
        process.exit(1);
      }
      process.stdin.setRawMode(false);
      resolve();
    })
  );
};

// let payload = {
//   connectableDevices: {
//     device1ID: {
//       id: "device1ID",
//       name: "device1Name",
//       type: "MBDevice",
//       variables: {
//         testVariable1ID: {
//           id: "testVariable1ID",
//           deviceId: "testDeviceID",
//           name: "testVariable1Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 123.456,
//           offset: 1,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable2ID: {
//           id: "testVariable2ID",
//           deviceId: "testDeviceID",
//           name: "testVariable2Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 321.654,
//           offset: 3,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable3ID: {
//           id: "testVariable3ID",
//           deviceId: "testDeviceID",
//           name: "testVariable3Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 789.654,
//           offset: 5,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable4ID: {
//           id: "testVariable4ID",
//           deviceId: "testDeviceID",
//           name: "testVariable4Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 123.456,
//           offset: 1,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 2,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable5ID: {
//           id: "testVariable5ID",
//           deviceId: "testDeviceID",
//           name: "testVariable5Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 321.654,
//           offset: 3,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 2,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable6ID: {
//           id: "testVariable6ID",
//           deviceId: "testDeviceID",
//           name: "testVariable6Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 789.654,
//           offset: 5,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 2,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable7ID: {
//           id: "testVariable7ID",
//           deviceId: "testDeviceID",
//           name: "testVariable7Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 123.456,
//           offset: 1,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 3,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable8ID: {
//           id: "testVariable8ID",
//           deviceId: "testDeviceID",
//           name: "testVariable8Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 321.654,
//           offset: 3,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 3,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable9ID: {
//           id: "testVariable9ID",
//           deviceId: "testDeviceID",
//           name: "testVariable9Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 789.654,
//           offset: 5,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 3,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//       },
//       calcElements: {},
//       alerts: {},
//       isActive: true,
//       ipAddress: "192.168.10.100",
//       portNumber: 502,
//       timeout: 500,
//     },

//     device2ID: {
//       id: "device2ID",
//       name: "device2Name",
//       type: "MBDevice",
//       variables: {
//         testVariable1ID: {
//           id: "testVariable1ID",
//           deviceId: "testDeviceID",
//           name: "testVariable1Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 123.456,
//           offset: 1,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable2ID: {
//           id: "testVariable2ID",
//           deviceId: "testDeviceID",
//           name: "testVariable2Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 321.654,
//           offset: 3,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable3ID: {
//           id: "testVariable3ID",
//           deviceId: "testDeviceID",
//           name: "testVariable3Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 789.654,
//           offset: 5,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//       },
//       calcElements: {},
//       alerts: {},
//       isActive: true,
//       ipAddress: "192.168.10.100",
//       portNumber: 503,
//       timeout: 500,
//     },
//   },
//   internalDevices: {},
//   agentDevices: {},
// };

// let payload2 = {
//   connectableDevices: {
//     device1ID: {
//       id: "device1ID",
//       name: "device1Name",
//       type: "MBDevice",
//       variables: {
//         testVariable1ID: {
//           id: "testVariable1ID",
//           deviceId: "testDeviceID",
//           name: "testVariable1Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 123.456,
//           offset: 7,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable2ID: {
//           id: "testVariable2ID",
//           deviceId: "testDeviceID",
//           name: "testVariable2Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 321.654,
//           offset: 9,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable3ID: {
//           id: "testVariable3ID",
//           deviceId: "testDeviceID",
//           name: "testVariable3Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 789.654,
//           offset: 11,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable4ID: {
//           id: "testVariable4ID",
//           deviceId: "testDeviceID",
//           name: "testVariable4Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 123.456,
//           offset: 7,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 2,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable5ID: {
//           id: "testVariable5ID",
//           deviceId: "testDeviceID",
//           name: "testVariable5Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 321.654,
//           offset: 9,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 2,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable6ID: {
//           id: "testVariable6ID",
//           deviceId: "testDeviceID",
//           name: "testVariable6Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 789.654,
//           offset: 11,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 2,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable7ID: {
//           id: "testVariable7ID",
//           deviceId: "testDeviceID",
//           name: "testVariable7Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 123.456,
//           offset: 7,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 3,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable8ID: {
//           id: "testVariable8ID",
//           deviceId: "testDeviceID",
//           name: "testVariable8Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 321.654,
//           offset: 9,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 3,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable9ID: {
//           id: "testVariable9ID",
//           deviceId: "testDeviceID",
//           name: "testVariable9Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 789.654,
//           offset: 11,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 3,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//       },
//       calcElements: {},
//       alerts: {},
//       isActive: true,
//       ipAddress: "192.168.10.100",
//       portNumber: 502,
//       timeout: 500,
//     },

//     device2ID: {
//       id: "device2ID",
//       name: "device2Name",
//       type: "MBDevice",
//       variables: {
//         testVariable1ID: {
//           id: "testVariable1ID",
//           deviceId: "testDeviceID",
//           name: "testVariable1Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 123.456,
//           offset: 7,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable2ID: {
//           id: "testVariable2ID",
//           deviceId: "testDeviceID",
//           name: "testVariable2Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 321.654,
//           offset: 9,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//         testVariable3ID: {
//           id: "testVariable3ID",
//           deviceId: "testDeviceID",
//           name: "testVariable3Name",
//           type: "MBSwappedFloat",
//           unit: "FakeUnit",
//           sampleTime: 1,
//           defaultValue: 789.654,
//           offset: 11,
//           length: 2,
//           read: true,
//           write: false,
//           readFCode: 3,
//           writeFCode: 16,
//           unitID: 1,
//           readAsSingle: false,
//           writeAsSingle: false,
//         },
//       },
//       calcElements: {},
//       alerts: {},
//       isActive: true,
//       ipAddress: "192.168.10.100",
//       portNumber: 503,
//       timeout: 500,
//     },
//   },
//   internalDevices: {},
//   agentDevices: {},
// };

let payload = {
  connectableDevices: {
    device1ID: {
      id: "device1ID",
      name: "device1Name",
      type: "MBDevice",
      variables: {
        testVariable1ID: {
          id: "testVariable1ID",
          deviceId: "testDeviceID",
          name: "testVariable1Name",
          type: "MBByteArray",
          unit: "FakeUnit",
          sampleTime: 1,
          defaultValue: [0, 0, 0, 0, 0, 0, 0, 0],
          offset: 1,
          length: 4,
          read: true,
          write: false,
          readFCode: 3,
          writeFCode: 16,
          unitID: 1,
          readAsSingle: false,
          writeAsSingle: false,
        },
      },
      calcElements: {},
      alerts: {},
      isActive: true,
      ipAddress: "192.168.10.100",
      portNumber: 502,
      timeout: 500,
    },
  },
  internalDevices: {},
  agentDevices: {},
};

const displayVariables = (device) => {
  for (let variable of Object.values(device.Variables)) {
    console.log(
      `${device.Name}: ${variable.Name}: ${variable.LastValueTick} : ${variable.Value}`
    );
  }
};

let exec = async () => {
  let project = new Project();
  await project.load(payload);
  setInterval(() => {
    for (let device of Object.values(project.Devices)) {
      displayVariables(device);
    }
  }, 1000);

  await keypress();

  // console.log("reloading");
  // await project.load(payload2);
  // console.log("reloaded");
};

exec();
